SELECT * FROM sales WHERE city = 'Pune';
SELECT * FROM sales WHERE city = 'Mumbai';
SELECT * FROM sales WHERE category= 'Electronics';
SELECT * FROM sales WHERE category= 'Fashion';
SELECT * FROM sales WHERE category= 'Sports';
SELECT product_name,price FROM sales WHERE price > 5000;
SELECT product_name,price FROM sales WHERE price < 5000;
SELECT customer_name FROM sales WHERE age > 25;
SELECT customer_name FROM sales WHERE age < 25;
SELECT product_name,rating FROM sales WHERE rating > 4.5;
SELECT * FROM sales WHERE payment_mode= 'UPI';
SELECT * FROM sales WHERE payment_mode= 'card';
SELECT * FROM sales WHERE payment_mode= 'cash';
SELECT * FROM sales WHERE category= 'Electronics' AND city='Pune';
SELECT * FROM sales WHERE category= 'Fashion' AND city='Mumbai';
SELECT * FROM sales WHERE gender= 'Female' AND city='Delhi';
SELECT * FROM sales WHERE gender= 'Male' AND city='Pune';
SELECT product_name FROM sales WHERE price BETWEEN 2000 AND 10000;
SELECT customer_name FROM sales WHERE age BETWEEN 24 AND 30;
SELECT * FROM sales WHERE order_date > '2026-01-20';