SELECT product_name FROM sales ORDER BY price;
SELECT product_name FROM sales ORDER BY price DESC;
SELECT customer_name FROM sales ORDER BY age;
SELECT customer_name FROM sales ORDER BY age DESC;
SELECT product_name FROM sales ORDER BY rating DESC;
SELECT product_name,price FROM sales where price = (SELECT MAX(price) FROM sales);
SELECT product_name,price FROM sales where price = (SELECT MIN(price) FROM sales);
SELECT product_name,rating FROM sales where rating = (SELECT MAX(rating) FROM sales);
SELECT * FROM sales WHERE order_date= (SELECT MAX(order_date) FROM sales);
SELECT * FROM sales WHERE order_date= (SELECT MIN(order_date) FROM sales);
SELECT * FROM sales LIMIT 5;
SELECT product_name,price FROM sales ORDER BY price DESC LIMIT 3;
SELECT product_name,rating FROM sales ORDER BY rating DESC LIMIT 5;
SELECT product_name, price FROM sales ORDER BY price DESC LIMIT 1 OFFSET 1;
SELECT product_name, price FROM sales ORDER BY price DESC LIMIT 1 OFFSET 2;
SELECT * FROM sales LIMIT 5,20;
SELECT * FROM sales LIMIT 5,5;
SELECT * FROM sales LIMIT 10,5;
SELECT * FROM sales LIMIT 15,5;
SELECT * FROM sales ORDER BY order_date DESC LIMIT 3;